# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Gateway_CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: |
        cd Gateway_Solution
        cd ./Patient_Services
        dotnet restore
    - name: Build
      run: |
        dotnet build --no-restore Gateway_Solution
        dotnet build --no-restore ./Patient_Services
    - name: Test
      run: |
        dotnet test --no-build --verbosity normal Gateway_Solution
        dotnet test --no-build --verbosity normal ./Patient_Services
